Add children, parents, ancestors, and descendants to OntologyTerm
alliance-genome/agr_curation_schema pull request #146
Opened 2022-07-13 02:45 UTC by chris-grove

I've labeled the slots "is_a_children", "is_a_parents", "is_a_ancestors", "is_a_descendants" at least as a placeholder. I think we do need to be specific about the relationship type.

2022-07-26 16:35 UTC, oblodgett approved these changes

2022-08-04 16:05 UTC, sierra-moxon requested changes
Will we have more slots in this class for every kind of closure?  part_of equivalents for example?  

What about a more generic data structure:

```
OntologyTermClosure:
   slots:
      - parent
      - child
      - relationship_type
 
slots:
   closure_type:
        range: enum_of_closures # ie: is_a, part_of, etc # depending on use cases, this could be straight from the RO, or an enumerated list of closure types.
```

2022-08-15 13:48 UTC, oblodgett commented
@sierra-moxon yes... but we let hibernate generate the join table, vs specifying it out here. So the class has the lists... however in the db there is only 2 tables to represent the closure for is_a.

2022-09-13 17:42 UTC, oblodgett commented
As stated in todays DQM meeting Parent - Child relationships for some mods are not considered as closure, but the ancestors - descendants are considered closure. In others both are considered closure. So here is what I propose


```
OntologyTerm:
   slots:
     - parents
     - children

OntologyTermClosure:
   slots:
      - ancestor
      - descendant 
      - distance_between # if we need it
      
OntologyTermRelationship:
   slots:
      - parent
      - child
      - relationship_type
 
slots:
   parents:
       range: OntologyTermRelationship
       multivalued: true
   children:
       range: OntologyTermRelationship
       multivalued: true
   ancestor:
       range: OntologyTerm
   descendant:
       range: OntologyTerm
   parent:
       range: OntologyTerm
   child:
       range: OntologyTerm
   relationship_type:
        range: ROTerm # We load the RO Ontology its a small ontology.
        
```

2022-09-20 00:04 UTC, sierra-moxon commented
This is purposefully failing for the moment - I'd like to talk about the test data and what we expect here.

2022-09-20 23:57 UTC, merged

2022-09-26 13:31 UTC, oblodgett commented on model/schema/ingest.yaml
> +      - ontology_closure_ingest_set
@chris-grove @sierra-moxon not sure we need an ingest for this considering the data is coming directly from owl files.